app:
  name: peony

database:
  user: root
  password: Xx2580..
  localhost: 127.0.0.1:3306
  db: peony
  option: charset=utf8mb4&parseTime=True&loc=Local

jwt:
  secret: peony
  iss: peony
  sub: peony
  exp: 1800 # 单位秒

redis:
  addr: 127.0.0.1:6379
  pass: ""
  db: 0

pay:
  alipay:
    app_id: 9021000123603301

email:
  name: peony
  host: smtp.163.com
  port: 465
  username: scrooge335121@163.com
  password: IAZIPPWQHXCUQOAX
  codeExp: 300